export const SA_CHART_OF_ACCOUNTS = [
  // Assets (1000-1999)
  { code: "1000", name: "Cash on Hand", type: "asset", is_vat_applicable: false, is_tax_deductible: false },
  { code: "1010", name: "Petty Cash", type: "asset", is_vat_applicable: false, is_tax_deductible: false },
  { code: "1020", name: "Cash Float", type: "asset", is_vat_applicable: false, is_tax_deductible: false },
  { code: "1100", name: "Standard Bank - Current Account", type: "asset", is_vat_applicable: false, is_tax_deductible: false },
  { code: "1110", name: "FNB - Current Account", type: "asset", is_vat_applicable: false, is_tax_deductible: false },
  { code: "1120", name: "ABSA - Current Account", type: "asset", is_vat_applicable: false, is_tax_deductible: false },
  { code: "1130", name: "Nedbank - Current Account", type: "asset", is_vat_applicable: false, is_tax_deductible: false },
  { code: "1140", name: "Capitec - Current Account", type: "asset", is_vat_applicable: false, is_tax_deductible: false },
  { code: "1150", name: "Bank - Savings Account", type: "asset", is_vat_applicable: false, is_tax_deductible: false },
  { code: "1160", name: "Bank - Investment Account", type: "asset", is_vat_applicable: false, is_tax_deductible: false },
  { code: "1200", name: "Accounts Receivable", type: "asset", is_vat_applicable: false, is_tax_deductible: false },
  { code: "1210", name: "Allowance for Doubtful Debts", type: "asset", is_vat_applicable: false, is_tax_deductible: false },
  { code: "1220", name: "Notes Receivable", type: "asset", is_vat_applicable: false, is_tax_deductible: false },
  { code: "1230", name: "Interest Receivable", type: "asset", is_vat_applicable: false, is_tax_deductible: false },
  { code: "1300", name: "Inventory - Raw Materials", type: "asset", is_vat_applicable: true, is_tax_deductible: false },
  { code: "1310", name: "Inventory - Work in Progress", type: "asset", is_vat_applicable: true, is_tax_deductible: false },
  { code: "1320", name: "Inventory - Finished Goods", type: "asset", is_vat_applicable: true, is_tax_deductible: false },
  { code: "1330", name: "Inventory - Consumables", type: "asset", is_vat_applicable: true, is_tax_deductible: false },
  { code: "1340", name: "Inventory - Spare Parts", type: "asset", is_vat_applicable: true, is_tax_deductible: false },
  { code: "1400", name: "Prepaid Expenses", type: "asset", is_vat_applicable: true, is_tax_deductible: false },
  { code: "1410", name: "Prepaid Rent", type: "asset", is_vat_applicable: true, is_tax_deductible: false },
  { code: "1420", name: "Prepaid Insurance", type: "asset", is_vat_applicable: true, is_tax_deductible: false },
  { code: "1430", name: "Deposits Paid", type: "asset", is_vat_applicable: false, is_tax_deductible: false },
  { code: "1500", name: "Land", type: "asset", is_vat_applicable: true, is_tax_deductible: false },
  { code: "1510", name: "Buildings", type: "asset", is_vat_applicable: true, is_tax_deductible: false },
  { code: "1520", name: "Accumulated Depreciation - Buildings", type: "asset", is_vat_applicable: false, is_tax_deductible: false },
  { code: "1530", name: "Plant & Machinery", type: "asset", is_vat_applicable: true, is_tax_deductible: false },
  { code: "1540", name: "Accumulated Depreciation - Plant", type: "asset", is_vat_applicable: false, is_tax_deductible: false },
  { code: "1600", name: "Motor Vehicles", type: "asset", is_vat_applicable: true, is_tax_deductible: false },
  { code: "1610", name: "Accumulated Depreciation - Vehicles", type: "asset", is_vat_applicable: false, is_tax_deductible: false },
  { code: "1700", name: "Furniture & Fixtures", type: "asset", is_vat_applicable: true, is_tax_deductible: false },
  { code: "1710", name: "Accumulated Depreciation - Furniture", type: "asset", is_vat_applicable: false, is_tax_deductible: false },
  { code: "1800", name: "Computer Equipment", type: "asset", is_vat_applicable: true, is_tax_deductible: false },
  { code: "1810", name: "Accumulated Depreciation - Computers", type: "asset", is_vat_applicable: false, is_tax_deductible: false },
  { code: "1820", name: "Computer Software", type: "asset", is_vat_applicable: true, is_tax_deductible: false },
  { code: "1830", name: "Accumulated Amortization - Software", type: "asset", is_vat_applicable: false, is_tax_deductible: false },
  { code: "1900", name: "Goodwill", type: "asset", is_vat_applicable: false, is_tax_deductible: false },
  { code: "1910", name: "Patents & Trademarks", type: "asset", is_vat_applicable: true, is_tax_deductible: false },
  { code: "1920", name: "Long-term Investments", type: "asset", is_vat_applicable: false, is_tax_deductible: false },
  
  // Liabilities (2000-2999)
  { code: "2000", name: "Accounts Payable", type: "liability", is_vat_applicable: false, is_tax_deductible: false },
  { code: "2010", name: "Trade Creditors", type: "liability", is_vat_applicable: false, is_tax_deductible: false },
  { code: "2100", name: "VAT Output (15%)", type: "liability", is_vat_applicable: false, is_tax_deductible: false },
  { code: "2110", name: "VAT Input", type: "liability", is_vat_applicable: false, is_tax_deductible: false },
  { code: "2120", name: "VAT Control Account", type: "liability", is_vat_applicable: false, is_tax_deductible: false },
  { code: "2200", name: "PAYE Payable", type: "liability", is_vat_applicable: false, is_tax_deductible: false },
  { code: "2210", name: "UIF Payable", type: "liability", is_vat_applicable: false, is_tax_deductible: false },
  { code: "2220", name: "SDL Payable (Skills Development Levy)", type: "liability", is_vat_applicable: false, is_tax_deductible: false },
  { code: "2230", name: "Provident Fund Payable", type: "liability", is_vat_applicable: false, is_tax_deductible: false },
  { code: "2240", name: "Medical Aid Payable", type: "liability", is_vat_applicable: false, is_tax_deductible: false },
  { code: "2250", name: "Pension Fund Payable", type: "liability", is_vat_applicable: false, is_tax_deductible: false },
  { code: "2300", name: "Short-term Loan", type: "liability", is_vat_applicable: false, is_tax_deductible: false },
  { code: "2310", name: "Bank Overdraft", type: "liability", is_vat_applicable: false, is_tax_deductible: false },
  { code: "2315", name: "PAYE (Tax Payable)", type: "liability", is_vat_applicable: false, is_tax_deductible: false },
  { code: "2320", name: "Credit Card Payable", type: "liability", is_vat_applicable: false, is_tax_deductible: false },
  { code: "2400", name: "Long-term Loan", type: "liability", is_vat_applicable: false, is_tax_deductible: false },
  { code: "2410", name: "Mortgage Payable", type: "liability", is_vat_applicable: false, is_tax_deductible: false },
  { code: "2420", name: "Vehicle Finance", type: "liability", is_vat_applicable: false, is_tax_deductible: false },
  { code: "2500", name: "Accrued Expenses", type: "liability", is_vat_applicable: false, is_tax_deductible: false },
  { code: "2510", name: "Accrued Salaries", type: "liability", is_vat_applicable: false, is_tax_deductible: false },
  { code: "2520", name: "Accrued Interest", type: "liability", is_vat_applicable: false, is_tax_deductible: false },
  { code: "2600", name: "Deferred Revenue", type: "liability", is_vat_applicable: true, is_tax_deductible: false },
  { code: "2700", name: "Provisions", type: "liability", is_vat_applicable: false, is_tax_deductible: false },
  
  // Equity (3000-3999)
  { code: "3000", name: "Owner's Capital", type: "equity", is_vat_applicable: false, is_tax_deductible: false },
  { code: "3100", name: "Share Capital", type: "equity", is_vat_applicable: false, is_tax_deductible: false },
  { code: "3200", name: "Retained Earnings", type: "equity", is_vat_applicable: false, is_tax_deductible: false },
  { code: "3300", name: "Current Year Earnings", type: "equity", is_vat_applicable: false, is_tax_deductible: false },
  { code: "3400", name: "Drawings", type: "equity", is_vat_applicable: false, is_tax_deductible: false },
  { code: "3500", name: "Dividends Declared", type: "equity", is_vat_applicable: false, is_tax_deductible: false },
  
  // Revenue/Income (4000-4999)
  { code: "4000", name: "Sales Revenue - Local", type: "revenue", is_vat_applicable: true, is_tax_deductible: true },
  { code: "4010", name: "Sales Revenue - Export", type: "revenue", is_vat_applicable: true, is_tax_deductible: true },
  { code: "4100", name: "Service Revenue", type: "revenue", is_vat_applicable: true, is_tax_deductible: true },
  { code: "4110", name: "Consulting Revenue", type: "revenue", is_vat_applicable: true, is_tax_deductible: true },
  { code: "4120", name: "Professional Fees", type: "revenue", is_vat_applicable: true, is_tax_deductible: true },
  { code: "4200", name: "Interest Income", type: "revenue", is_vat_applicable: false, is_tax_deductible: true },
  { code: "4210", name: "Dividend Income", type: "revenue", is_vat_applicable: false, is_tax_deductible: false },
  { code: "4300", name: "Other Income", type: "revenue", is_vat_applicable: true, is_tax_deductible: true },
  { code: "4310", name: "Sundry Income", type: "revenue", is_vat_applicable: true, is_tax_deductible: true },
  { code: "4400", name: "Rental Income", type: "revenue", is_vat_applicable: true, is_tax_deductible: true },
  { code: "4500", name: "Commission Income", type: "revenue", is_vat_applicable: true, is_tax_deductible: true },
  { code: "4600", name: "Discount Received", type: "revenue", is_vat_applicable: true, is_tax_deductible: true },
  { code: "4700", name: "Foreign Exchange Gain", type: "revenue", is_vat_applicable: false, is_tax_deductible: true },
  
  // Cost of Sales (5000-5999)
  { code: "5000", name: "Cost of Goods Sold", type: "expense", is_vat_applicable: true, is_tax_deductible: true },
  { code: "5100", name: "Purchases - Local", type: "expense", is_vat_applicable: true, is_tax_deductible: true },
  { code: "5110", name: "Purchases - Import", type: "expense", is_vat_applicable: true, is_tax_deductible: true },
  { code: "5120", name: "Supplier Returns", type: "expense", is_vat_applicable: true, is_tax_deductible: true },
  { code: "5200", name: "Freight & Delivery Inwards", type: "expense", is_vat_applicable: true, is_tax_deductible: true },
  { code: "5300", name: "Direct Labour", type: "expense", is_vat_applicable: false, is_tax_deductible: true },
  { code: "5400", name: "Manufacturing Overheads", type: "expense", is_vat_applicable: true, is_tax_deductible: true },
  { code: "5500", name: "Inventory Adjustments", type: "expense", is_vat_applicable: false, is_tax_deductible: true },
  { code: "5600", name: "Opening Stock", type: "expense", is_vat_applicable: false, is_tax_deductible: true },
  { code: "5700", name: "Closing Stock", type: "expense", is_vat_applicable: false, is_tax_deductible: true },
  
  // Operating Expenses (6000-6999)
  { code: "6000", name: "Salaries & Wages", type: "expense", is_vat_applicable: false, is_tax_deductible: true },
  { code: "6010", name: "Management Salaries", type: "expense", is_vat_applicable: false, is_tax_deductible: true },
  { code: "6020", name: "Staff Salaries", type: "expense", is_vat_applicable: false, is_tax_deductible: true },
  { code: "6030", name: "Overtime", type: "expense", is_vat_applicable: false, is_tax_deductible: true },
  { code: "6040", name: "Bonuses", type: "expense", is_vat_applicable: false, is_tax_deductible: true },
  { code: "6050", name: "Commission Paid", type: "expense", is_vat_applicable: false, is_tax_deductible: true },
  { code: "6100", name: "Rent Expense", type: "expense", is_vat_applicable: true, is_tax_deductible: true },
  { code: "6110", name: "Rates & Taxes", type: "expense", is_vat_applicable: false, is_tax_deductible: true },
  { code: "6120", name: "Levies", type: "expense", is_vat_applicable: false, is_tax_deductible: true },
  { code: "6200", name: "Utilities - Electricity", type: "expense", is_vat_applicable: true, is_tax_deductible: true },
  { code: "6210", name: "Utilities - Water", type: "expense", is_vat_applicable: true, is_tax_deductible: true },
  { code: "6220", name: "Utilities - Gas", type: "expense", is_vat_applicable: true, is_tax_deductible: true },
  { code: "6300", name: "Telephone & Internet", type: "expense", is_vat_applicable: true, is_tax_deductible: true },
  { code: "6310", name: "Postage & Courier", type: "expense", is_vat_applicable: true, is_tax_deductible: true },
  { code: "6400", name: "Insurance - General", type: "expense", is_vat_applicable: true, is_tax_deductible: true },
  { code: "6410", name: "Insurance - Vehicle", type: "expense", is_vat_applicable: true, is_tax_deductible: true },
  { code: "6420", name: "Insurance - Public Liability", type: "expense", is_vat_applicable: true, is_tax_deductible: true },
  { code: "6500", name: "Motor Vehicle Expenses", type: "expense", is_vat_applicable: true, is_tax_deductible: true },
  { code: "6510", name: "Vehicle Maintenance", type: "expense", is_vat_applicable: true, is_tax_deductible: true },
  { code: "6520", name: "Vehicle License", type: "expense", is_vat_applicable: false, is_tax_deductible: true },
  { code: "6600", name: "Fuel & Oil", type: "expense", is_vat_applicable: false, is_tax_deductible: true },
  { code: "6700", name: "Repairs & Maintenance - Building", type: "expense", is_vat_applicable: true, is_tax_deductible: true },
  { code: "6710", name: "Repairs & Maintenance - Equipment", type: "expense", is_vat_applicable: true, is_tax_deductible: true },
  { code: "6800", name: "Office Supplies", type: "expense", is_vat_applicable: true, is_tax_deductible: true },
  { code: "6810", name: "Stationery & Printing", type: "expense", is_vat_applicable: true, is_tax_deductible: true },
  { code: "6820", name: "Cleaning & Hygiene", type: "expense", is_vat_applicable: true, is_tax_deductible: true },
  { code: "6900", name: "Bank Charges", type: "expense", is_vat_applicable: true, is_tax_deductible: true },
  { code: "6910", name: "Accounting Fees", type: "expense", is_vat_applicable: true, is_tax_deductible: true },
  { code: "6920", name: "Legal Fees", type: "expense", is_vat_applicable: true, is_tax_deductible: true },
  { code: "6930", name: "Consulting Fees", type: "expense", is_vat_applicable: true, is_tax_deductible: true },
  { code: "6940", name: "Audit Fees", type: "expense", is_vat_applicable: true, is_tax_deductible: true },
  { code: "7000", name: "Advertising & Marketing", type: "expense", is_vat_applicable: true, is_tax_deductible: true },
  { code: "7010", name: "Website & Digital Marketing", type: "expense", is_vat_applicable: true, is_tax_deductible: true },
  { code: "7020", name: "Promotions", type: "expense", is_vat_applicable: true, is_tax_deductible: true },
  { code: "7100", name: "Training & Development", type: "expense", is_vat_applicable: true, is_tax_deductible: true },
  { code: "7110", name: "Staff Welfare", type: "expense", is_vat_applicable: true, is_tax_deductible: true },
  { code: "7120", name: "Recruitment", type: "expense", is_vat_applicable: true, is_tax_deductible: true },
  { code: "7200", name: "Travel & Accommodation", type: "expense", is_vat_applicable: true, is_tax_deductible: true },
  { code: "7210", name: "Meals & Entertainment", type: "expense", is_vat_applicable: false, is_tax_deductible: false },
  { code: "7300", name: "Subscriptions & Memberships", type: "expense", is_vat_applicable: true, is_tax_deductible: true },
  { code: "7310", name: "Licenses & Permits", type: "expense", is_vat_applicable: false, is_tax_deductible: true },
  { code: "7400", name: "Depreciation Expense", type: "expense", is_vat_applicable: false, is_tax_deductible: true },
  { code: "7410", name: "Amortization Expense", type: "expense", is_vat_applicable: false, is_tax_deductible: true },
  { code: "7500", name: "Bad Debts", type: "expense", is_vat_applicable: true, is_tax_deductible: true },
  { code: "7510", name: "Provision for Bad Debts", type: "expense", is_vat_applicable: false, is_tax_deductible: false },
  { code: "7600", name: "Donations & Sponsorships", type: "expense", is_vat_applicable: false, is_tax_deductible: false },
  { code: "7700", name: "Security Services", type: "expense", is_vat_applicable: true, is_tax_deductible: true },
  { code: "7800", name: "Interest Expense", type: "expense", is_vat_applicable: false, is_tax_deductible: true },
  { code: "7900", name: "Foreign Exchange Loss", type: "expense", is_vat_applicable: false, is_tax_deductible: true },
  { code: "8000", name: "Sundry Expenses", type: "expense", is_vat_applicable: true, is_tax_deductible: true },
];
